
 const  stockSymbols = [
        { symbol: "RELIANCE.NS", name: "Reliance Industries" },
        { symbol: "HDFCBANK.NS", name: "HDFC Bank" },
        { symbol: "ICICIBANK.NS", name: "ICICI Bank" },
        { symbol: "INFY.NS", name: "Infosys" },
        { symbol: "TCS.NS", name: "Tata Consultancy Services" },
        { symbol: "ITC.NS", name: "ITC Limited" },
        { symbol: "LT.NS", name: "Larsen & Toubro" },
        { symbol: "SBIN.NS", name: "State Bank of India" },
        { symbol: "BHARTIARTL.NS", name: "Bharti Airtel" },
        { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
        { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever" },
        { symbol: "AXISBANK.NS", name: "Axis Bank" },
        { symbol: "BAJFINANCE.NS", name: "Bajaj Finance" },
        { symbol: "ASIANPAINT.NS", name: "Asian Paints" },
        { symbol: "MARUTI.NS", name: "Maruti Suzuki" },
        { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical" },
        { symbol: "ONGC.NS", name: "Oil and Natural Gas Corporation" },
        { symbol: "WIPRO.NS", name: "Wipro" },
        { symbol: "NTPC.NS", name: "NTPC Limited" },
        { symbol: "TITAN.NS", name: "Titan Company" },
        { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement" },
        { symbol: "NESTLEIND.NS", name: "Nestle India" },
        { symbol: "POWERGRID.NS", name: "Power Grid Corporation" },
        { symbol: "HCLTECH.NS", name: "HCL Technologies" },
        { symbol: "JSWSTEEL.NS", name: "JSW Steel" },
        { symbol: "ADANIENT.NS", name: "Adani Enterprises" },
        { symbol: "ADANIPORTS.NS", name: "Adani Ports" },
        { symbol: "GRASIM.NS", name: "Grasim Industries" },
        { symbol: "TATASTEEL.NS", name: "Tata Steel" },
        { symbol: "M&M.NS", name: "Mahindra & Mahindra" },
        { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance" },
        { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv" },
        { symbol: "COALINDIA.NS", name: "Coal India" },
        { symbol: "TECHM.NS", name: "Tech Mahindra" },
        { symbol: "BRITANNIA.NS", name: "Britannia Industries" },
        { symbol: "CIPLA.NS", name: "Cipla" },
        { symbol: "DIVISLAB.NS", name: "Divi's Laboratories" },
        { symbol: "DRREDDY.NS", name: "Dr Reddy's Laboratories" },
        { symbol: "HINDALCO.NS", name: "Hindalco Industries" },
        { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp" },
        { symbol: "BPCL.NS", name: "Bharat Petroleum" },
        { symbol: "EICHERMOT.NS", name: "Eicher Motors" },
        { symbol: "SHREECEM.NS", name: "Shree Cement" },
        { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals" },
        { symbol: "INDUSINDBK.NS", name: "IndusInd Bank" },
        { symbol: "SBILIFE.NS", name: "SBI Life Insurance" },
        { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto" },
        { symbol: "TATAMOTORS.NS", name: "Tata Motors" },
        { symbol: "UPL.NS", name: "UPL Limited" },
        { symbol: "TRENT.NS", name: "Trent Limited" },
        { symbol: "ADANIPOWER.NS", name: "Adani Power" },
        { symbol: "DMART.NS", name: "Avenue Supermarts (DMart)" },
        { symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life" },
        { symbol: "NAUKRI.NS", name: "Info Edge (Naukri)" },
        { symbol: "GODREJCP.NS", name: "Godrej Consumer Products" },
        { symbol: "PIDILITIND.NS", name: "Pidilite Industries" },
        { symbol: "DLF.NS", name: "DLF Limited" },
        { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance" },
        { symbol: "COLPAL.NS", name: "Colgate Palmolive India" },
        { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
        { symbol: "INDIGO.NS", name: "InterGlobe Aviation (IndiGo)" },
        { symbol: "PNB.NS", name: "Punjab National Bank" },
        { symbol: "ABB.NS", name: "ABB India" },
        { symbol: "BERGEPAINT.NS", name: "Berger Paints" },
        { symbol: "CANBK.NS", name: "Canara Bank" },
        { symbol: "INDHOTEL.NS", name: "Indian Hotels Company" },
        { symbol: "YESBANK.NS", name: "Yes Bank" },
        { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals" },
        { symbol: "TVSMOTOR.NS", name: "TVS Motor Company" },
        { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma" },
        { symbol: "MANAPPURAM.NS", name: "Manappuram Finance" },
        { symbol: "BEL.NS", name: "Bharat Electronics" },
        { symbol: "IOC.NS", name: "Indian Oil Corporation" },
        { symbol: "SAIL.NS", name: "Steel Authority of India" },
        { symbol: "PETRONET.NS", name: "Petronet LNG" },
        { symbol: "GAIL.NS", name: "GAIL India" },
        { symbol: "HAVELLS.NS", name: "Havells India" },
        { symbol: "AMBUJACEM.NS", name: "Ambuja Cements" },
        { symbol: "ACC.NS", name: "ACC Limited" },
        { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance" },
        { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment" },
        { symbol: "LUPIN.NS", name: "Lupin Limited" },
        { symbol: "LTIM.NS", name: "LTIMindtree" },
        { symbol: "BANDHANBNK.NS", name: "Bandhan Bank" },
        { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank" },
        { symbol: "PAGEIND.NS", name: "Page Industries" },
        { symbol: "JINDALSTEL.NS", name: "Jindal Steel & Power" },
        { symbol: "NMDC.NS", name: "NMDC Limited" },
        { symbol: "CONCOR.NS", name: "Container Corporation of India" },
        { symbol: "IGL.NS", name: "Indraprastha Gas" },
        { symbol: "MPHASIS.NS", name: "Mphasis" },
        { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals" },
        { symbol: "ALKEM.NS", name: "Alkem Laboratories" },
        { symbol: "AUBANK.NS", name: "AU Small Finance Bank" },
        { symbol: "POLYCAB.NS", name: "Polycab India" },
        { symbol: "IPCALAB.NS", name: "IPCA Laboratories" },
        { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance" }
    ]
export default stockSymbols;